# Generated by Django 5.0.4 on 2024-04-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admn_id', models.CharField(max_length=20, unique=True)),
                ('admn_name', models.CharField(max_length=150)),
                ('admn_phone', models.CharField(max_length=50)),
                ('admn_email', models.EmailField(max_length=254)),
                ('admn_addres', models.CharField(max_length=250)),
                ('admn_password', models.CharField(max_length=150)),
                ('last_login', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
