# Generated by Django 5.0.4 on 2024-05-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0004_alter_attendance_unique_together_attendance_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendanceregister',
        ),
    ]
