# Generated by Django 5.0.4 on 2024-04-23 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeInfo',
        ),
    ]
