# Generated by Django 5.0.4 on 2024-04-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_delete_employeeinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20, unique=True)),
                ('emp_name', models.CharField(max_length=150)),
                ('emp_phone', models.CharField(max_length=50)),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_addres', models.CharField(max_length=250)),
                ('emp_job', models.CharField(max_length=50)),
                ('emp_password', models.CharField(max_length=150)),
                ('emp_department', models.CharField(max_length=150)),
                ('emp_created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
