# Generated by Django 5.0.4 on 2024-05-06 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeinfo',
            old_name='emp_created_date',
            new_name='last_login',
        ),
    ]
