# Generated by Django 5.0.4 on 2024-05-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_rename_emp_created_date_employeeinfo_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addattendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('createddatetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
