# Generated by Django 5.0.4 on 2024-05-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_addattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addattendance',
            name='latitude',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='addattendance',
            name='longitude',
            field=models.CharField(max_length=100),
        ),
    ]
