# Generated by Django 5.0.4 on 2024-05-09 17:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_addattendance_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addattendance',
            name='createddatetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
