# Generated by Django 5.0.4 on 2024-05-10 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_submission_delete_addattendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='submission_datetime',
            new_name='saved_datetime',
        ),
    ]
