# Generated by Django 5.0.4 on 2024-05-28 06:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_logotsave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logotsave',
            name='saved_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='submission',
            name='saved_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
