# Generated by Django 5.0.4 on 2024-04-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_id', models.CharField(max_length=20, unique=True)),
                ('hr_name', models.CharField(max_length=150)),
                ('hr_phone', models.CharField(max_length=50)),
                ('hr_email', models.EmailField(max_length=254)),
                ('hr_addres', models.CharField(max_length=250)),
                ('hr_password', models.CharField(max_length=150)),
                ('hr_created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
