# Generated by Django 5.0.4 on 2024-04-28 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_hrinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hrinfo',
            old_name='hr_created_date',
            new_name='last_login',
        ),
    ]
